TOKEN = "5639340683:AAFT6k0E1HbvtKPWX31fklQ5pR91DArce90"
api_key = "sk-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"
start_msg = "Hello! I am a bot that can generate responses to your questions and requests. Just send me a message and I will try my best to help you."
date_time_format = "%Y-%m-%d %H:%M:%S"
separator = "##################################################"
