TOKEN = "5639340683:AAFT6k0E1HbvtKPWX31fklQ5pR91DArce90"
api_key = "ssk-78AXPVBOReuIIYIqlN8oT3BlbkFJN2jY8yK1Kxm7uOGnVt12"
start_msg = "Hello! I am a bot that can generate responses to your questions and requests. Just send me a message and I will try my best to help you."
date_time_format = "%Y-%m-%d %H:%M:%S"
separator = "##################################################"
